---
title: "Full Analysis"
format: html
---

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(stringr)

fish_df <- read_excel("C:/Users/brody/Desktop/Brody Thesis Project/Data Sets/Pal_Cage_fishvide_bm_v1.xlsx")


cover_df <- read_excel("C:/Users/brody/Desktop/Brody Thesis Project/Data Sets/Pal_ExCag_Dat_BR_V1.xlsx") %>%
  mutate(
    Treatment = str_trim(Treatment),
    Treatment = dplyr::recode(Treatment, "Control" = "Con")
  )
```



```{r}
library(readxl)
library(dplyr)
library(writexl)

# 1) Read + keep only the columns you need
total_area_1 <- total_area %>%
  select(Block, Treatment, Year, total_coral_area_cm2) %>%
  mutate(Year = as.integer(Year) + 2017)

mean_indiv_growth_agg_1 <- mean_indiv_growth_agg %>%
  select(Block, Treatment, Year, mean_indiv_growth_cm2, n_corals) %>%
  mutate(Year = as.integer(Year) + 2017)

cover_df_1 <- cover_df %>%
  select(Year, Block, Treatment,
         CCA_calcareous, Fleshy_MA, `Lobo/Peys`, Scleractinian, SPAT, TAS) %>%
  mutate(Year = as.integer(Year))

fish_df_1 <- fish_df %>%
  select(Year, Block, Treatment, Grazerdetritivore, Herbivore_Sc_Br) %>%
  mutate(Year = as.integer(Year))

# 2) Join everything together (keep all rows from total_area_norep)
combined_df <- total_area_1 %>%
  left_join(mean_indiv_growth_agg_1, by = c("Year", "Block", "Treatment")) %>%
  left_join(cover_df_1, by = c("Year", "Block", "Treatment")) %>%
  left_join(fish_df_1, by = c("Year", "Block", "Treatment")) %>%
  select(
    Year, Block, Treatment,
    total_coral_area_cm2, mean_indiv_growth_cm2, n_corals,
    CCA_calcareous, Fleshy_MA, `Lobo/Peys`, Scleractinian, SPAT, TAS,
    Grazerdetritivore, Herbivore_Sc_Br
  )

# 3) Export
write_xlsx(combined_df, "combined_coral_benthic_fish.xlsx")
```

