---
title: "Growth Anal"
format: html
---

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(stringr)

combined_df <- read_excel("C:/Users/brody/Desktop/Brody Thesis Project/Data Sets/combined_coral_benthic_fish.xlsx")

```


```{r}
library(dplyr)

combined_prop <- combined_df1 %>%
  left_join(
    mean_prop_growth_x %>%
      select(Year, Block, Treatment, mean_prop_growth),
    by = c("Year", "Block", "Treatment")
  )
```


```{r}
combined_prop_1 <- combined_prop %>%
  filter(!Year %in% c(2018, 2019, 2024)) |> 
   mutate(
    Year = factor(Year),
    Treatment = factor(Treatment),
    Block = factor(Block)
  )
```





```{r}
combined_df1 <- combined_df %>%
  filter(!Year %in% c(2018, 2024)) |> 
   mutate(
    Year = factor(Year),
    Treatment = factor(Treatment),
    Block = factor(Block)
  )
```

```{r}
combined_df1 <- combined_df1 %>%
  mutate(
    Treatment = factor(
      Treatment,
      levels = c("Con", "1x1", "2x2", "TopOnly")
    )
  )
```


```{r}
combined_df2 <- combined_df1 %>%
  mutate(across(
    c(CCA_calcareous, Fleshy_MA, `Lobo/Peys`,
      Scleractinian, SPAT, TAS,
      Grazerdetritivore, Herbivore_Sc_Br),
    scale
  ))
```

###############################################################################################################################

## Treatment and Year


```{r}
library(lme4)

m1 <- lmer(
  mean_indiv_growth_cm2 ~ Treatment + (1 | Block),
  data = combined_df2,
  REML = FALSE
)

m2 <- lmer(
  mean_indiv_growth_cm2 ~ Year + (1 | Block),
  data = combined_df2,
  REML = FALSE
)

m3 <- lmer(
  mean_indiv_growth_cm2 ~ Treatment + Year + (1 | Block),
  data = combined_df2,
  REML = FALSE
)

m4 <- lmer(
  mean_indiv_growth_cm2 ~ Treatment * Year + (1 | Block),
  data = combined_df2,
  REML = FALSE
)

anova(m1, m2, m3, m4)
```




###############################################################################################################################





## Coral Growth using gaussian mixed model (simplest), maybe switch to gamma if residuals dont fit 

```{r}
full_growth <- lmer(
  mean_prop_growth ~ #Treatment +
  Year +
  CCA_calcareous +
  Fleshy_MA +
  `Lobo/Peys` +
  #Scleractinian +
  SPAT +
  TAS +
  Grazerdetritivore +
  Herbivore_Sc_Br +
  (1|Block),
  data = combined_prop_1
)
```

```{r, warning=FALSE, message=FALSE}
library(MuMIn)

options(na.action = "na.fail")

dredge_prop <- dredge(full_growth, fixed = "Year")

best_prop <- get.models(dredge_prop, 1)[[1]]

#summary(dredge_prop)
summary(best_prop)
```










```{r}
library(performance)


growth_model <- lmerTest::lmer(
  mean_prop_growth ~
    #Treatment +
    Year +
    CCA_calcareous +
    Fleshy_MA +
    `Lobo/Peys` +
    #Scleractinian +
    SPAT +
    TAS +
    #Grazerdetritivore +
    #Herbivore_Sc_Br +
    (1|Block),
  data = combined_prop_1
)

fixed_effects <- broom.mixed::tidy(growth_model, effects = "fixed")
r2 <- MuMIn::r.squaredGLMM(growth_model)
aic_val <- AIC(growth_model)
collinearity <- performance::check_collinearity(growth_model)
normality <- performance::check_normality(growth_model)
heteroscedasticity <- performance::check_heteroscedasticity(growth_model)

fixed_effects
r2
aic_val
collinearity
normality
heteroscedasticity

anova(growth_model)

```
```{r}
#| fig-height: 30
#| fig-width: 15
performance::check_model(growth_model)

#setwd("C:/Users/brody/Desktop/Brody Thesis Project/Figures")
#ggsave("Check Model Growth.jpg", width = 8, height = 8) 
```

```{r}
plot(growth_model)
qqnorm(resid(growth_model))
qqline(resid(growth_model))
```






