---
title: "Total Area Anal"
format: html
---

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(stringr)

combined_df <- read_excel("C:/Users/brody/Desktop/Brody Thesis Project/Data Sets/combined_coral_benthic_fish.xlsx") |>
  mutate(
    Year = factor(Year),
    Treatment = factor(
      Treatment,
      levels = c("Con", "1x1", "2x2", "TopOnly")
    ),
    Block = factor(Block)
  )


```

```{r}
combined_df1 <- combined_df %>%
  filter(!Year %in% c(2018, 2023, 2024))
```


```{r}
combined_df2 <- combined_df1 %>%
  mutate(across(
    c(CCA_calcareous, Fleshy_MA, `Lobo/Peys`,
      Scleractinian, SPAT, TAS,
      Grazerdetritivore, Herbivore_Sc_Br),
    scale
  ))
```

###############################################################################################################################

## Treatment and Year

```{r}
library(lme4)

t1 <- glmer(
  total_coral_area_cm2 ~ Treatment + (1 | Block),
  data = combined_df2,
  family = Gamma(link="log"),
)

t2 <- glmer(
  total_coral_area_cm2 ~ Year + (1 | Block),
  data = combined_df2,
  family = Gamma(link="log"),
)

t3 <- glmer(
  total_coral_area_cm2 ~ Treatment + Year + (1 | Block),
  data = combined_df2,
  family = Gamma(link="log"),
)

t4 <- glmer(
  total_coral_area_cm2 ~ Treatment * Year + (1 | Block),
 data = combined_df2,
  family = Gamma(link="log")
)

anova(t1, t2, t3, t4)
```

```{r}
area_treat_year_model <- lme4::glmer(
  total_coral_area_cm2 ~
    Treatment +
    Year +
    (1 | Block),
  data = combined_df2,
  family = Gamma(link = "log")
)

fixed_effects <- broom.mixed::tidy(area_treat_year_model, effects = "fixed")

r2 <- MuMIn::r.squaredGLMM(area_treat_year_model)

aic_val <- AIC(area_treat_year_model)

collinearity <- performance::check_collinearity(area_treat_year_model)


dispersion <- performance::check_overdispersion(area_treat_year_model)

car::Anova(area_treat_year_model, type = "III")

fixed_effects
r2
aic_val
collinearity
dispersion


library(DHARMa)

sim_res <- simulateResiduals(area_treat_year_model)

plot(sim_res)
testUniformity(sim_res)
testDispersion(sim_res)
```


#### Get data set from total area plot code

```{r}
total_area_summary <- total_area_p1 %>%
  group_by(Year) %>%
  summarise(mean_area = mean(mean_total_coral_area_cm2, na.rm = TRUE))

total_area_summary %>%
  mutate(change = mean_area - lag(mean_area))
```





```{r}
library(emmeans)
library(multcomp)
library(multcompView)
emm_response <- emmeans(area_treat_year_model, ~ Treatment, type = "response")
emm_response
pairs(emm_response)
cld(emm_response, Letters = letters)
```





```{r}
library(ggplot2)
library(dplyr)
library(emmeans)
library(scales)

# estimated marginal means on response scale
emm_treat <- emmeans(area_treat_year_model, ~ Treatment, type = "response")

# pairwise letter groups
emm_letters <- cld(emm_treat, Letters = letters)

# turn into data frame
emm_df <- as.data.frame(emm_letters)

# clean spacing in .group column
emm_df <- emm_df %>%
  mutate(.group = trimws(.group))

# make treatment order match your preferred order
# emm_df$Treatment <- factor(emm_df$Treatment,
#                            levels = c("Con", "1x1", "2x2", "TopOnly"))
# 
# combined_df2$Treatment <- factor(combined_df2$Treatment,
#                                  levels = c("Con", "1x1", "2x2", "TopOnly"))

# position for letters above error bars
emm_df <- emm_df %>%
  mutate(letter_y = asymp.UCL * 1.3)

# plot
ggplot() +
  # raw data
  geom_jitter(
    data = combined_df2,
    aes(x = Treatment, y = total_coral_area_cm2, color = Treatment, shape = Treatment),
    width = 0.12,
    height = 0,
    alpha = 0.6,
    size = 2
  ) +
  scale_shape_manual(values = c(
    "Con" = 19,
    "1x1" = 18,
    "2x2" = 17,
    "TopOnly" = 15
  ))+

  # error bars (colored, solid)
  geom_errorbar(
    data = emm_df,
    aes(x = Treatment, ymin = asymp.LCL, ymax = asymp.UCL, color = Treatment),
    width = 0.12,
    linewidth = 1
  ) +

  # emmeans points (colored fill + black outline)
  geom_point(
    data = emm_df,
    aes(x = Treatment, y = response, fill = Treatment),
    size = 3,
    shape = 21,           # allows fill + outline
    color = "black",      # outline
    stroke = 1.2
  ) +

  # letters
  geom_text(
    data = emm_df,
    aes(x = Treatment, y = letter_y, label = .group),
    size = 6
  ) +

  scale_color_manual(values = c(
    "Con" = "black",
    "1x1" = "darkorchid4",
    "2x2" = "darkred",
    "TopOnly" = "deepskyblue2"
  )) +

  scale_fill_manual(values = c(
    "Con" = "black",
    "1x1" = "darkorchid4",
    "2x2" = "darkred",
    "TopOnly" = "deepskyblue2"
  )) +

  scale_y_continuous() +

  labs(
    x = "Treatment",
    y = expression("Total Coral Area (cm"^2*", log scale)"),
    title = "Estimated Coral Area by Treatment"
  ) +
  scale_x_discrete(labels = c(
  "Con" = "Control",
  "1x1" = "Small",
  "2x2" = "Medium",
  "TopOnly" = "Large"
))+

  theme_classic(base_size = 14) +
  theme(legend.position = "none")

# setwd("C:/Users/brody/Desktop/Brody Thesis Project/Figures")
# ggsave("Area by Treatment.jpg", width = 8, height = 5) 
```









## Use total coral area model from other document 





###############################################################################################################################




## Total area using gamma glm
```{r}
library(lme4)

full_area <- glmer(
  total_coral_area_cm2 ~ #Treatment +
  Year + 
  CCA_calcareous +
  Fleshy_MA +
  `Lobo/Peys` +
  #Scleractinian +
  SPAT +
  TAS +
  Grazerdetritivore +
  Herbivore_Sc_Br +
  (1|Block),
  data = combined_df2,
  family = Gamma(link="log")
)
```



## Dredge 

```{r message=FALSE, warning=FALSE}
library(MuMIn)

options(na.action = "na.fail")

dredge(full_area, fixed = "Year")

#best_area <- get.models(dredge_area, 1)[[1]]

#summary(dredge_area)
#summary(best_area)
```







```{r}
total_area_model <- lme4::glmer(
  total_coral_area_cm2 ~
    #Treatment +
    Year +
    #CCA_calcareous +
    #Fleshy_MA +
    #`Lobo/Peys` +
    #Scleractinian +
    #SPAT +
    TAS +
    #Grazerdetritivore +
    #Herbivore_Sc_Br +
    (1 | Block),
  data = combined_df1,
  family = Gamma(link = "log")
)



# Fixed effects
broom.mixed::tidy(total_area_model, effects = "fixed")

# R2
MuMIn::r.squaredGLMM(total_area_model)

# AIC
AIC(total_area_model)

# Collinearity
performance::check_collinearity(total_area_model)

## Dispersion Test
performance::check_overdispersion(total_area_model)

# Residual diagnostics (IMPORTANT)
library(DHARMa)
sim_res <- simulateResiduals(total_area_model)
plot(sim_res)
testUniformity(sim_res)
testDispersion(sim_res)

# Proper significance test
car::Anova(total_area_model, type = "III")
```


```{r}
library(ggeffects)
library(ggplot2)

tas_pred <- ggpredict(total_area_model, terms = c("TAS", "Year"))
tas_pred <- tas_pred %>%
  rename(Year = group)
```



```{r}
ggplot(tas_pred, aes(x = x, y = predicted)) +
  geom_line(size = 1.2, color = "darkblue") +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),
              alpha = 0.25, fill = "deepskyblue") +
  labs(
    x = "TAS Cover",
    y = "Predicted Total Coral Area (cm²)",
    title = "Effect of TAS on Total Coral Area"
  ) +
  theme_classic(base_size = 14)
```







```{r}
ggplot() +
  geom_point(
    data = combined_df1,
    aes(x = TAS, y = total_coral_area_cm2,
        color = Treatment, shape = Treatment, fill = Treatment),
    alpha = 0.8
  ) +
  geom_line(
    data = tas_pred,
    aes(x = x, y = predicted),
    color = "black", linewidth = 1.2
  ) +
  geom_ribbon(
    data = tas_pred,
    aes(x = x, ymin = conf.low, ymax = conf.high),
    fill = "gray17", alpha = 0.25
  ) +
  scale_color_manual(
  values = c(
    "Con" = "black",
    "1x1" = "darkorchid4",
    "2x2" = "darkred",
    "TopOnly" = "deepskyblue2"
  ),
  labels = c(
    "Con" = "Control",
    "1x1" = "Small",
    "2x2" = "Medium",
    "TopOnly" = "Large"
  )
) +
scale_shape_manual(
  values = c(
    "Con" = 21,
    "1x1" = 22,
    "2x2" = 23,
    "TopOnly" = 24
  ),
  labels = c(
    "Con" = "Control",
    "1x1" = "Small",
    "2x2" = "Medium",
    "TopOnly" = "Large"
  )
)+
   scale_fill_manual(
    values = c(
      "1x1"     = "darkorchid4",
      "2x2"     = "darkred",
      "TopOnly" = "deepskyblue2",
      "Con"     = "black"
    ),
    labels = c(
      "1x1"     = "Small",
      "2x2"     = "Medium",
      "TopOnly" = "Large",
      "Con"     = "Control"
    )
  ) +
  scale_y_log10() +
  facet_wrap(~ Year, ncol = 4) +
  labs(
    x = "Turf and Sediment Cover (% cover)",
    y = expression(bold("Total Coral Area (cm"^2*", log scale)")),
    title = "Effect of TAS Cover on Total Coral Area"
  ) +
  theme_classic(base_size = 14) +
  theme(legend.position = "bottom",
        plot.title = element_text(face = "bold", size = 14),
    axis.title = element_text(face = "bold"),
    axis.text = element_text(color = "black"))

setwd("C:/Users/brody/Desktop/Brody Thesis Project/Figures")
ggsave("TAS and Area.jpg", width = 8, height = 5) 
```







